"""Prepared exact graphs, immutable weight preparation and integer residual LUTs.

MAC kernels, their reduction order, and all format oracles are unchanged. Every
integer residual lookup is generated by those same exact scalar oracles. Other
domains execute the frozen reference operator. No FP32 surrogate is introduced.
"""
from __future__ import annotations

from collections.abc import Sequence
import copy
from fractions import Fraction
import hashlib
import json
from math import prod
from types import MappingProxyType

import numpy as np

from public.experiments.registry.identity import canonical_json_bytes
from public.inference.native import prepare_tensor
from public.inference.operators.dispatch import Operators
from public.inference.reference import detector, operators as ref
from public.inference.reference.arithmetic import decode, encode, format_named
from public.inference.tensor import Encoding, SharedEncoding, Tensor, observe_quantization, parse_encoding
from public.quantization.graph.executable import validate_graph
from tools.phase3.integer_store import integer_store
from tools.exact_execution_v2.mixed_store import mixed_integer_store


def tensor_sha256(tensor):
    """Canonical tensor hash without copying/re-walking validated integer codes.

    Tensor construction already verifies every shape/code, and encodings emit
    explicit scale strings. JSON's finite check remains enabled. Serialization
    is byte-identical to canonical_json_bytes(tensor.document()), including its
    final newline; no generic configuration validation is bypassed.
    """
    payload = {'shape': tensor.shape, 'codes': tensor.codes, 'encoding': tensor.encoding.document()}
    encoded = json.dumps(payload, ensure_ascii=False, allow_nan=False, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256((encoded + '\n').encode('utf-8')).hexdigest()


def freeze(value):
    if isinstance(value, dict):
        return MappingProxyType({k: freeze(v) for k, v in value.items()})
    if isinstance(value, (tuple, list)):
        return tuple(freeze(v) for v in value)
    return value


def thaw(value):
    if isinstance(value, MappingProxyType):
        return {k: thaw(v) for k, v in value.items()}
    if isinstance(value, tuple):
        return [thaw(v) for v in value]
    return value


class IndexedValues(Sequence):
    """Lazy exact pre-store values, including all diagnostic sample positions."""
    def __init__(self, indices, table):
        self.indices, self.table = indices, table

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, index):
        if isinstance(index, slice):
            return tuple(self.table[int(i)] for i in self.indices[index])
        return self.table[int(self.indices[index])]


class IntegerResiduals:
    def __init__(self):
        self.alignments, self.sums = {}, {}

    @staticmethod
    def supported(encoding):
        return (isinstance(encoding, Encoding) and encoding.axis is None
                and encoding.block_size is None and format_named(encoding.format).family == 'integer')

    def align(self, tensor, alignment):
        key = (tensor.encoding, alignment)
        if key not in self.alignments:
            values = tuple(decode(format_named(tensor.encoding.format), c, tensor.encoding.scales[0])
                           for c in range(1 << format_named(tensor.encoding.format).bits))
            codes = np.asarray([encode(format_named(alignment.format), v, alignment.scales[0]) for v in values],
                               dtype=np.uint8)
            codes.flags.writeable = False
            self.alignments[key] = values, codes
        values, codes = self.alignments[key]
        indices = np.asarray(tensor.codes, dtype=np.uint8)
        stored = Tensor(tensor.shape, tuple(codes[indices].tolist()), alignment)
        return observe_quantization(IndexedValues(indices, values), stored)

    def add(self, left, right, *, operation, output, accumulator=None, alignment=None):
        if (operation != 'add' or not all(self.supported(e) for e in (left.encoding, right.encoding, output, alignment))
                or accumulator not in {'int32_accumulator', 'int64_accumulator'}):
            return ref.elementwise(left, right, operation=operation, output=output,
                                   accumulator=accumulator, alignment=alignment)
        if left.shape != right.shape:
            raise ValueError('elementwise shapes must match; broadcasting must be explicit')
        fmt = format_named(alignment.format)
        if (not fmt.manifest['signed'] or fmt.manifest['numeric']['fractional_bits'] != 0
                or fmt.manifest['numeric'].get('zero_point', 0) != 0):
            return ref.elementwise(left, right, operation=operation, output=output,
                                   accumulator=accumulator, alignment=alignment)
        a, b = self.align(left, alignment), self.align(right, alignment)
        key = (alignment, accumulator, output)
        minimum = -(1 << fmt.bits)
        if key not in self.sums:
            acc = format_named(accumulator)
            scale = alignment.scales[0]
            # A signed b-bit pair has sums in [-2**b, 2**b-2]. Evaluate
            # accumulator rounding as well; do not infer equivalence from width.
            values = tuple(acc.rounded(Fraction(s) * scale, scale=scale)
                           for s in range(minimum, -minimum - 1))
            codes = np.asarray([encode(format_named(output.format), v, output.scales[0]) for v in values], dtype=np.uint8)
            codes.flags.writeable = False
            self.sums[key] = values, codes
        def signed_codes(tensor):
            codes = np.asarray(tensor.codes, dtype=np.int16)
            return np.where(codes >= 1 << (fmt.bits - 1), codes - (1 << fmt.bits), codes)
        indices = signed_codes(a) + signed_codes(b) - minimum
        values, codes = self.sums[key]
        stored = Tensor(left.shape, tuple(codes[indices].tolist()), output)
        return observe_quantization(IndexedValues(indices, values), stored)


class PreparedOperators(Operators):
    def __init__(self, backend, library, constants):
        super().__init__(backend, library)
        self.constants = {id(tensor): tensor for tensor in constants.values()}
        self.prepared = {}

    def _prepare(self, tensor, unscaled=False):
        key = (id(tensor), unscaled)
        constant = self.constants.get(id(tensor)) is tensor
        if constant and key in self.prepared:
            return self.prepared[key]
        try:
            result = prepare_tensor(tensor, unscaled=unscaled)
            if constant:
                result.array.flags.writeable = False
        except ValueError:
            result = (tuple(decode(format_named(tensor.encoding.format), c) for c in tensor.codes)
                      if unscaled else tensor.values())
        if constant:
            self.prepared[key] = result
        return result

    def _domains(self, inputs, weights, accumulator):
        acc = ref._accumulator(accumulator)
        if acc.family != 'integer':
            return self._prepare(inputs), self._prepare(weights), (Fraction(1),) * weights.shape[0]
        if inputs.encoding.axis is not None or weights.encoding.axis not in {None, 0} or weights.encoding.block_size:
            raise ValueError('INT32 native reduction requires per-tensor activations and tensor/channel weights')
        scales = tuple(inputs.encoding.scales[0] * weights.encoding.scale_at(weights.shape, (c,) + (0,) * (len(weights.shape)-1))
                       for c in range(weights.shape[0]))
        return self._prepare(inputs, True), self._prepare(weights, True), scales

    def _store(self, states, shape, accumulator, scales, bias, activation, output):
        result = integer_store(states, shape, accumulator, scales, bias, activation, output)
        if result is None:
            result = mixed_integer_store(states, shape, accumulator, scales, bias, activation, output, fallback=super()._store)
        return result if result is not None else super()._store(states, shape, accumulator, scales, bias, activation, output)


class PreparedGraph:
    """One worker-owned immutable graph snapshot; inputs are checked every call.

    Caller mutations to the source document cannot change this graph. Caches
    belong to this instance, are bounded by graph domains, and are not shared
    between jobs. Instantiate a new graph to change any constant or attribute.
    """
    def __init__(self, document, *, backend='reference', library=None):
        snapshot = copy.deepcopy(document)
        validate_graph(snapshot)
        self.graph_sha256 = hashlib.sha256(canonical_json_bytes(snapshot)).hexdigest()
        self._inputs = MappingProxyType({k: parse_encoding(v) for k, v in snapshot['inputs'].items()})
        self._constants = MappingProxyType({k: Tensor.from_document(v) for k, v in snapshot['constants'].items()})
        nodes = []
        for node in snapshot['nodes']:
            attrs = copy.deepcopy(node['attrs'])
            for key in ('output', 'alignment', 'input_encoding'):
                if key in attrs:
                    attrs[key] = parse_encoding(attrs[key])
            nodes.append((node['name'], node['op'], tuple(node['inputs']), freeze(attrs), freeze(node)))
        self._nodes, self._outputs = tuple(nodes), tuple(snapshot['outputs'])
        self.backend = backend
        self._operators = PreparedOperators(backend, library, self._constants)
        self._residuals = IntegerResiduals()

    def execute(self, inputs, *, observer=None):
        if set(inputs) != set(self._inputs):
            raise ValueError('graph input names mismatch')
        for name, expected in self._inputs.items():
            actual = inputs[name].encoding
            compatible = (actual.format == expected.format and actual.axis == expected.axis and actual.block_size == expected.block_size
                          if isinstance(expected, SharedEncoding) else actual == expected)
            if not compatible:
                raise ValueError('graph input encoding mismatch')
        values = {**inputs, **self._constants}
        traces, execution_modes = {}, {}
        for name, op, edges, frozen_attrs, frozen_node in self._nodes:
            node, attrs = thaw(frozen_node), thaw(frozen_attrs)
            if observer is not None and hasattr(observer, 'begin_node'):
                observer.begin_node(node)
            args = [values[edge] for edge in edges]
            if op == 'reshape':
                source = args[0]
                if source.encoding.axis is not None:
                    raise ValueError('reshape of scaled axes requires an explicit domain conversion')
                if prod(attrs['shape']) != prod(source.shape):
                    raise ValueError('reshape changes tensor element count')
                value = Tensor(tuple(attrs['shape']), source.codes, source.encoding)
            elif op == 'lut':
                if args[0].encoding != attrs.pop('input_encoding'):
                    raise ValueError('LUT input domain mismatch')
                function = attrs.pop('function')
                if tuple(attrs['table']) != ref.nonlinear_lut(args[0].encoding, attrs['output'], function):
                    raise ValueError('LUT contents do not match declared function/domain')
                value = ref.apply_lut(*args, **attrs)
            elif op in {'conv2d', 'depthwise_conv2d', 'linear', 'block_conv2d'}:
                value = getattr(self._operators, op)(*args, **attrs)
                execution_modes[name] = ('reference_rational' if self._operators.native is None else self._operators.native.last_strategy)
            elif op == 'elementwise':
                value = self._residuals.add(*args, **attrs)
            elif hasattr(detector, op):
                value = getattr(detector, op)(*args, **attrs)
            else:
                value = getattr(ref, op)(*args, **attrs)
            values[name] = value
            traces[name] = {'shape': list(value.shape), 'encoding': value.encoding.document(),
                            'sha256': tensor_sha256(value)}
            if observer is not None:
                observer(node, value)
        return {'outputs': {name: values[name] for name in self._outputs}, 'layers': traces,
                'backend': self.backend, 'execution_modes': execution_modes, 'graph_sha256': self.graph_sha256}
